apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-filestore-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: filestore-storage-class