apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-storage-class
provisioner: filestore.csi.google.com
allowVolumeExpantion: true
reclaimPolicy: Retain
volumeBindingMode: waitForFirstConsumer
parameter:
  tier: standard
  network: default