apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-pd-standard-rwo-sc
provisioner: pd-csi.storage.gke.io 
parameters:
  type: pd-standard
  replication-type: none
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true