apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default  # Specify the namespace for the RoleBinding
subjects:
  - kind: User
    name: "jane.doe"  # Specify the user or service account to bind to the role
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # The Role being referenced
  apiGroup: rbac.authorization.k8s.io
