apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebs-app
  template:
    metadata:
      labels:
        app: ebs-app
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: ebs-storage
      volumes:
        - name: ebs-storage
          persistentVolumeClaim:
            claimName: ebs-pvc